# Generated by Django 4.2.29 on 2026-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
